services:
  - type: web
    name: dna-repair-backend
    env: python
    repo: https://github.com/yourusername/dna-repair-agent
    branch: master
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
